apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: homepage
    namespace: homepage
    labels:
        app.kubernetes.io/name: homepage
    annotations:
        cert-manager.io/cluster-issuer: dns01-letsencrypt-prod
        gethomepage.dev/description: Dynamically Detected Homepage
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Cluster Management
        gethomepage.dev/icon: homepage.png
        gethomepage.dev/name: Homepage
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    ingressClassName: zirconsys-ingress
    tls:
      - hosts:
          - dash.zirconsys.cloud
        secretName: dash-tls-certificate-ingress
    rules:
        - host: "dash.zirconsys.cloud"
          http:
              paths:
                  - path: "/"
                    pathType: Prefix
                    backend:
                        service:
                            name: homepage
                            port:
                                number: 3000
