apiVersion: v1
kind: Service
metadata:
  name: nas-service-v4 # example value
  namespace: zirconsys-ingress
spec:
  type: ExternalName
  externalName: 10.10.10.10
  ports:
    - name: nas-5000   # example value
      protocol: TCP 
      port: 5000     # example value
    - name: nas-5001   # example value
      protocol: TCP
      port: 5001