---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: zirconsys-ingress
  name: dsm-ingress
  labels:
    app.kubernetes.io/name: synology
  annotations:
    cert-manager.io/cluster-issuer: dns01-letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: zirconsys-ingress
  tls:
    - hosts:
        - dsm.zirconsys.cloud
      secretName: dsm-tls-certificate-ingress
  rules:
    - host: dsm.zirconsys.cloud
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: nas-service-v4
                port:
                  number: 5000